default: &default
  adapter: mysql2
  pool: 12
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci

development:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER_NAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
